# Netlify設定ファイル
# https://docs.netlify.com/configure-builds/file-based-configuration/

# プラグイン設定
# 注：netlify-plugin-prerender-spaは全ページを処理して時間がかかりすぎるため
# 一旦コメントアウトし、別の方法を検討
# [[plugins]]
#   package = "netlify-plugin-prerender-spa"

[build]
  # ビルドコマンド
  command = "npm run build"
  
  # ビルド出力ディレクトリ
  publish = "dist"
  
  # Node.jsバージョン
  environment = { NODE_VERSION = "18" }

# 静的アセットの404を防ぐためのリダイレクト
# 重要: force = false で実際のファイルが存在する場合は優先される
[[redirects]]
  from = "/episodes/js/*"
  to = "/js/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/episodes/css/*"
  to = "/css/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/episodes/assets/*"
  to = "/assets/:splat"
  status = 200
  force = false

# その他のサブディレクトリからのアセット参照も修正
[[redirects]]
  from = "/*/js/*"
  to = "/js/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*/css/*"
  to = "/css/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*/assets/*"
  to = "/assets/:splat"
  status = 200
  force = false

# SPAリダイレクト設定（推奨設定）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Basic認証用のリダイレクト（Netlify Functionsで処理）
[[redirects]]
  from = "/api/auth"
  to = "/.netlify/functions/auth"
  status = 200

# robots.txt の動的生成
[[redirects]]
  from = "/robots.txt"
  to = "/.netlify/functions/robots"
  status = 200

# sitemap.xml の動的生成
[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200

# ヘッダー設定
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# HTMLファイルのキャッシュ制御（短時間キャッシュ）
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=300, stale-while-revalidate=86400"

# JSとCSSファイルのキャッシュ制御（長期キャッシュ、ただし更新検知）
[[headers]]
  for = "/js/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/css/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# XMLサイトマップの正しいContent-Type設定
[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"

# ========================================
# 環境別設定
# ========================================

# 本番環境（mainブランチ）
[context.production]
  environment = { APP_ENV = "production", VITE_ENVIRONMENT = "production", VITE_SUPABASE_URL = "https://awaarykghpylggygkiyp.supabase.co", VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3YWFyeWtnaHB5bGdneWdraXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3OTE0MDksImV4cCI6MjA2NzM2NzQwOX0.J1dXm0eHB8RaqT_UnOI_zY7q1UyTaV4lLJtQT6EHhOE" }
  command = "npm run build"

# ステージング環境（developブランチ）
[context."develop"]
  environment = { APP_ENV = "staging", VITE_ENVIRONMENT = "staging", VITE_SUPABASE_URL = "https://ounloyykptsqzdpbsnpn.supabase.co", VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91bmxveXlrcHRzcXpkcGJzbnBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MjIzODMsImV4cCI6MjA3MDI5ODM4M30.VpSq034vLWHH3n_W-ikJyho6BuwY6UahN52V9US5n0U" }
  command = "npm run build"
  
  # Basic認証設定（staging環境）
  [[context."develop".redirects]]
    from = "/*"
    to = "/.netlify/functions/auth"
    status = 200

# プレビュー環境（PRごと）  
[context.deploy-preview]
  environment = { APP_ENV = "preview", VITE_ENVIRONMENT = "preview", VITE_SUPABASE_URL = "https://ounloyykptsqzdpbsnpn.supabase.co", VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91bmxveXlrcHRzcXpkcGJzbnBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MjIzODMsImV4cCI6MjA3MDI5ODM4M30.VpSq034vLWHH3n_W-ikJyho6BuwY6UahN52V9US5n0U" }
  command = "npm run build"
  
  # Basic認証設定（preview環境）
  [[context.deploy-preview.redirects]]
    from = "/*" 
    to = "/.netlify/functions/auth"
    status = 200

# ブランチデプロイ（develop以外のブランチ）
[context.branch-deploy]
  environment = { APP_ENV = "staging", VITE_ENVIRONMENT = "staging" }
  command = "npm run build"